// Generated by CoffeeScript 1.7.1
(function() {
  var prefix;

  prefix = ".utstat";

  module.exports = {
    encoding: "utf8",
    site_file: "site" + prefix + ".json",
    index_file: "index" + prefix + ".json",
    dependencies_file: ".dependencies" + prefix + ".json",
    extension: ".html"
  };

}).call(this);
