// Generated by CoffeeScript 1.7.1
(function() {
  var Utstat, build, config, path;

  build = require('./build');

  config = require('./config');

  path = require('path');

  Utstat = (function() {
    function Utstat() {}

    Utstat.prototype.build = function(dir, callback) {
      var builder;
      dir = path.resolve(dir);
      builder = new build.Builder(config, dir);
      return builder.build(callback);
    };

    return Utstat;

  })();

  module.exports = new Utstat;

}).call(this);
