// Generated by CoffeeScript 1.7.1
(function() {
  var Utstat, build, config, path;

  build = require('./build');

  config = require('./config');

  path = require('path');

  Utstat = (function() {
    function Utstat() {}

    Utstat.prototype.build = function(dir, option, callback) {
      var builder, conf, key, value;
      if ((callback == null) && "function" === typeof option) {
        callback = option;
        option = {};
      }
      conf = Object.create(config);
      for (key in option) {
        value = option[key];
        conf[key] = value;
      }
      dir = path.resolve(dir);
      builder = new build.Builder(conf, dir);
      return builder.build(callback);
    };

    return Utstat;

  })();

  module.exports = new Utstat;

}).call(this);
